### ISSUE TITLE
A matrix with a power of -1 should evaluate its inverse

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#103]

**Comment by WhiteBlackGoose** [comment]
But now it finds -1 power of all its elements (piecewise). It also works piecewisely for product. Actually, do we really need piecewise operations?

I think we will change it to matrix operations (like you said). It will be soon released then!

**Comment by WhiteBlackGoose** [comment]
Hehe, no. We will add separate nodes, but the power operation on matrix remains elementwise, :duck:
