### ISSUE TITLE
Use System.Numerics.BigInteger in AngouriMath.Core.Numerix.IntegerNumber

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#110]
In the `Numbers` project, there is this item `Consider integer-overflow`. Using `System.Numerics.BigInteger` instead of `long` can ensure that all integers can be represented, eliminating integer overflow.

Also, why is `decimal` used inside `AngouriMath.Core.Numerix.RealNumber` instead of `double`? `decimal` is used for high-precision calculation, providing up to 28\~29 significant digits, but its range is much more limited, at 10⁻²⁸\~10²⁸, while `double` can cover values in 10⁻³⁰⁰\~10³⁰⁰ with less precision, at about 15\~16 significant digits. We are not calculating money here, so a wider range instead of a higher precision is a better trade-off.

And why was the namespace changed from `AngouriMath.Core.Numeric` to `AngouriMath.Core.Numerix`? Why not `AngouriMath.Core.Numerics`? It is an actual word.

**Comment by WhiteBlackGoose** [comment]
Decimal is used because we indeed rather need high precision than that high values. 
As of the namespace, I just like this name. :)
I will consider transitioning to BigInteger

**Comment by MomoDeve** [comment]
We need high precision. For example, after variable substitution in analytically found roots of quartic equation results are very inaccurate. Decimal reduces rounding errors and helps to still get exqct results like 1 + 2i instead of 0.99999999 + 2.000000001i
Working with large numbers is bad in both cases, as for values like 10^30 precision loss is too big even for double values

**Comment by Happypig375** [comment]
In `AngouriMath.Core.Numerix.Number` `NumberOperators.cs`, you are making `System.Numerics.Complex`es from `decimal`s to perform calculations, but `System.Numerics.Complex` uses two `double`s to store the number, so you are not gaining any precision here. In contrast, precision is actually lost after calculation.

**Comment by WhiteBlackGoose** [comment]
There's even a card in TODO to develop powers for decimal-based complex. We will do it soon

**Comment by Happypig375** [comment]
Hmmm. It didn't mention operations other than powers. Guess it's the reason I missed it.

**Comment by Happypig375** [comment]
But given that you are going to implement custom operations anyway, consider using a [BigDecimal](https://gist.github.com/JcBernack/0b4eef59ca97ee931a2f45542b9ff06d) so that both precision and range can be achieved with a larger implementation effort.

**Comment by WhiteBlackGoose** [comment]
Done
