### ISSUE TITLE
But given that you are going to implement custom operations anyway, consider using a [BigDecimal](https://gist.github.com/JcBernack/0b4eef59ca97ee931a2f45542b9ff06d) so that both precision and range can be achieved with a larger implementation effort.

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#112]
But given that you are going to implement custom operations anyway, consider using a [BigDecimal](https://gist.github.com/JcBernack/0b4eef59ca97ee931a2f45542b9ff06d) so that both precision and range can be achieved with a larger implementation effort.

_Originally posted by @Happypig375 in https://github.com/asc-community/AngouriMath/issues/110#issuecomment-634750042_

**Comment by WhiteBlackGoose** [comment]
The only problem with it that we need Complex based on "BigDecimal", otherwise it's not needed

**Comment by WhiteBlackGoose** [comment]
Also, it's not a good enought implementation of BigDecimal. It lacks of some functions like sin, cos... as well as other implementations of BigDecimal that I could find so far.

**Comment by MomoDeve** [comment]
I did a quick search, what about this lib? https://github.com/peteroupc/Numbers
@WhiteBlackGoose

**Comment by WhiteBlackGoose** [comment]
Added
