### ISSUE TITLE
SolveEquation hangs while solving trigonometry

### ISSUE THREAD

**Issue by MomoDeve** [asc-community/AngouriMath#114]
```cs
Entity e = "sin(2x + 2) + sin(x + 1) - a";
Console.WriteLine(e.SolveEquation("x"));
```
Equation **is solved** analytically through trigonometric solver, but result is so huge that [Simplify()](https://github.com/asc-community/AngouriMath/blob/master/AngouriMath/Functions/Algebra/EquationSolver/Analytical/AnalyticalSolver.cs#L467) hangs forever in this function

**Comment by WhiteBlackGoose** [comment]
Fixed
