### ISSUE TITLE
i*i Simplify-> i^2 but not -1

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#118]

**Comment by Happypig375** [comment]
i^3 does simplify to -i though.

**Comment by WhiteBlackGoose** [comment]
Why i*i should be i^2? "i" is a number, like 5 or sqrt(16). So if -1 is simpler than i*i, which is true, it simplifies to -1

**Comment by Happypig375** [comment]
Hmmm. Might be something wrong on my end. Lemme check.

**Comment by Happypig375** [comment]
@WhiteBlackGoose 
```cs
void M() {
  var i = new NumberEntity(MathS.i);
  var i2 = i * i;
  var simplified = i2.Simplify();
  throw new System.Exception(simplified.Latexise()); // {i}^{2}
}

**Comment by WhiteBlackGoose** [comment]
Did you pull the last version? Your code returns -1 in mine

**Comment by WhiteBlackGoose** [comment]
Also, off-topic. Are you sure you need \times thing for Latexisation? I will keep it as it is because you, as an active user, need it. I'm just curious whether you really need it, because it doesn't look cute

**Comment by Happypig375** [comment]
Do you suggest `\cdot`? I'm also ok with that.

**Comment by Happypig375** [comment]
After pulling latest master, there are still problems:
```cs
    void M() {
      var i = new NumberEntity(MathS.i);
      var i2 = MathS.Pow(i, 0);
      var simplified = i2.Simplify();
      throw new System.Exception(simplified.Latexise()); // {\left(i\right)}^{0}
    }
```

**Comment by Happypig375** [comment]
>Also, off-topic. Are you sure you need \times thing for Latexisation? I will keep it as it is because you, as an active user, need it. I'm just curious whether you really need it, because it doesn't look cute

>Do you suggest \cdot? I'm also ok with that.

Or if you want implicit multiplication, just remember to take care of e.g. `2\times a\times 2` needs to display as `2a\times 2`.

**Comment by WhiteBlackGoose** [comment]
throwing Exception turns out to be not the best way to debug.
```cs
throw new System.Exception(simplified.Latexise());
```
is not the same as
```cs
var s = simplified.Latexise();
throw new System.Exception(s);
```
Try the last one or use Console or whatever like that.

**Comment by Happypig375** [comment]
```cs
    void M() {
      var i = new NumberEntity(MathS.i);
      var i0 = MathS.Pow(i, 0);
      var simplified = i0.Simplify();
      var latex = simplified.Latexise(); // {\left(i\right)}^{0}
      throw new System.Exception(latex);
    }
```
?

**Comment by WhiteBlackGoose** [comment]
Fixed

**Comment by Happypig375** [comment]
@WhiteBlackGoose Not fixed for i^(-1)

**Comment by Happypig375** [comment]
Nvm. My problem.
