### ISSUE TITLE
MathS.Sets.Interval(1, 1) is null

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#128]

**Comment by WhiteBlackGoose** [comment]
Fixed.
Use MathS.Sets.Element to create one-piece element. Or do it implictly via
```
Piece a = 3;
```

**Comment by Happypig375** [comment]
MathS.Sets.Interval(1, 1) still returns null. It could simplify to a OneElementPiece on Eval though.

**Comment by WhiteBlackGoose** [comment]
Okay, I'll add throwing exception on Interval(1, 1)
