### ISSUE TITLE
Exception is thrown when solving expr / expr

### ISSUE THREAD

**Issue by MomoDeve** [asc-community/AngouriMath#135]
```cs
Entity expr = "(x - 1)/(x - 1)";
Console.WriteLine(expr.SolveEquation("x"));
```
same problem for `(x - 1) / ((x - 1) * (x - 1))`, `(x - 1) / (x^2 - 1)`

**Comment by siriak** [comment]
Which exception is thrown? And which behavior is expected? x = 1 cannot be a solution because the ratio isn't defined at point 1.

**Comment by MomoDeve** [comment]
> Which exception is thrown? And which behavior is expected? x = 1 cannot be a solution because the ratio isn't defined at point 1.

It throws NullReferenceException: Set object was null. Thats definitely not intentional behaviour

**Comment by WhiteBlackGoose** [comment]
@MomoDeve fixed.
@siriak my initial idea was that 0 / +oo is fine so the logic was (0 / (1 / 0)) = (0 / +oo) = 0. I reconsidered it by saying that any operation with at least one indefinite operand returns indefinite result, so there's no roots for (x + 1)/((x + 2)/(x + 1))
