### ISSUE TITLE
oo/0 should be NaN instead of oo

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#137]

**Comment by WhiteBlackGoose** [comment]
Why?

**Comment by Happypig375** [comment]
Division by 0?

**Comment by WhiteBlackGoose** [comment]
That results in indefinite result of oo?

**Comment by Happypig375** [comment]
Also, 2/oo and -2/oo should be 0.

**Comment by Happypig375** [comment]
>That results in indefinite result of oo?

Operation: oo/0
Expected: NaN
Actual: oo

**Comment by WhiteBlackGoose** [comment]
That used to be true until I realized that I can't afford operations that return definite results from indefinite operands.

**Comment by WhiteBlackGoose** [comment]
yes, you expected that, I have another opinion on it, since +1 / 0 = +oo, +oo / 0 = +oo

**Comment by Happypig375** [comment]
Hmmm.

**Comment by Happypig375** [comment]
Should `+1 / 0 = +oo, +oo / 0 = +oo` be a thing? We don't support signed zeroes.

**Comment by WhiteBlackGoose** [comment]
What do you mean? If we divide by zero, we look at the numerator

**Comment by Happypig375** [comment]
>we look at the numerator to get the sign

Zero is neither positive or negative so you shouldn't treat it like a positive number.

**Comment by Happypig375** [comment]
In limits, when approaching 0 from the negatives, 0 is considered to be negative. When approaching 0 from the positives, 0 is considered to be positive. When outside of limits, 0 is neither positive nor negative.

**Comment by WhiteBlackGoose** [comment]
Technically, unless we get to rings, 1 / 0 is non-defined at all, you're right. But for general convenience we define n / 0 as +oo for n > 0, -oo for n < 0, and NaN for n = 0

**Comment by Happypig375** [comment]
>That used to be true until I realized that I can't afford operations that return definite results from indefinite operands.

You are constructing new `RealNumber`s in the SuperSwitches. What prevents you from doing it?

**Comment by WhiteBlackGoose** [comment]
It doesn't make sense, there was an issue that was just right about it. If we let an operation with indefinite operands return a definite result, there might be a solution for (x-1) / ((x - 3) / (x-1)), you see, x = 1, because 0 / (-2 / 0) = 0. That doesn't make sense because since (-2 / 0) is indefinite (not NaN, but still indefinite), the whole expression cannot be definite

**Comment by Happypig375** [comment]
> But for general convenience we define n / 0 as +oo for n > 0, -oo for n < 0, and NaN for n = 0

However, all other sources, e.g. Wolfram Alpha and Mathway, all consider these undefined. They return 0 for `2/oo` and `-2/oo` though.

**Comment by WhiteBlackGoose** [comment]
WA returns infinity for 3 / 0, but some kind of indefinite infinity. I don't think it's a big difference. As of 2 / oo, I'll consider your thoughts, but I still find illogical that an indefinite operation itself might be equal to a definite number

**Comment by Happypig375** [comment]
>WA returns infinity for 3 / 0, but some kind of indefinite infinity. 

It is Complex Infinity, aka the unsigned infinity in Riemann spheres.

**Comment by Happypig375** [comment]
>I still find illogical that an indefinite operation itself might be equal to a definite number

Take the limit from both sides and you will arrive on the same result. This is not true for `lim_(x→0)2/x`. One side says `+oo`, another says `-oo`.

**Comment by WhiteBlackGoose** [comment]
Okay, I will think about it

**Comment by WhiteBlackGoose** [comment]
I considered it all, but didn't change my opinion.
1) 1 / oo = NaN because it's not a limit, as you say, it's rather an operation of division. We might add limits in the future, but we can't define "/" with limits in normal ariphmetic expressions. 

Otherwise, 
(x + 1) / ((x + 3) / (x + 1)) would have a root of -1:
0 / (2 / 0) = 0 / (oo) = 0
Because (x + 1) / ((x + 3) / (x + 1)) is not a limit for x -> -1, it's an analytically defined expression, and if once an undefined operand appears, the whole expression must be undefined as well

In WA they assumed you look for Limit for 1 / oo, so you saw 0 as an answer

2) oo / 0 -> oo will be kept for now as well (we don't pretend that something / 0 is something definite, we rather define division by zero with another indefinite result). Maybe we will change it when will implement limits

**Comment by Happypig375** [comment]
>Otherwise,
(x + 1) / ((x + 3) / (x + 1)) would have a root of -1:
0 / (2 / 0) = 0 / (oo) = 0
Because (x + 1) / ((x + 3) / (x + 1)) is not a limit for x -> -1, it's an analytically defined expression, and if once an undefined operand appears, the whole expression must be undefined as well

No. 0 / (2 / 0) = 0 / undefined = undefined

>oo / 0 -> oo will be kept for now as well (we don't pretend that something / 0 is something definite, we rather define division by zero with another indefinite result). Maybe we will change it when will implement limits

That should be NaN. NaN is indefinite but is the correct answer because +oo and -oo have a known sign which is not the case here.

**Comment by Happypig375** [comment]
Go to https://en.wikipedia.org/wiki/Extended_real_number_line#Arithmetic_operations. A real number divided by infinity is clearly defined but not for division by zero. You are advocating for a mathematically unsound result.

**Comment by Happypig375** [comment]
For a division by zero to be defined, we have to support Wolfram Alpha's ComplexInfinity which is an unsigned infinity unlike our +oo and -oo. We would therefore support https://en.wikipedia.org/wiki/Projectively_extended_real_line in addition to the Affinely Extended Real Line currently in use.

**Comment by Happypig375** [comment]
That ComplexInfinity is also the infinity in https://en.wikipedia.org/wiki/Riemann_sphere which is an extension of the Projective Extended Real Line into the Complex plane.

**Comment by WhiteBlackGoose** [comment]
> No. 0 / (2 / 0) = 0 / undefined = undefined
I actually considered the two issues separately, well if we do both
1) Define 1/ oo as 0
2) Define {} / 0 as NaN
Then it makes sense

**Comment by Happypig375** [comment]
Does "minor bug" mean "easy to fix", "lower priority" or "lower impact"?

**Comment by WhiteBlackGoose** [comment]
All of them. Anyway, fixed
