### ISSUE TITLE
What's the best way to implement Settings?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#141]
Since one major update, there's static class MathS.Settings. With it, you can set necessary values to fit your requirements.

**How does it work now?**

Basically, each setting is a stack. To set a new value, you write
```cs
MathS.Settings.MaxAbsNumeratorOrDenominatorValue.Set(20000000);
```
Which pushes the value onto the stack
After you performed necessary operations, it's recommended to *Unset* it:
```cs
MathS.Settings.MaxAbsNumeratorOrDenominatorValue.Unset();
```

**What's the problem?**

Exceptions. If one is thrown between Set and Unset, and then it's caught, you will get unexpected behavior that is very hard to debug, for example:
```cs
public static void DoSomething()
{
    MathS.Settings.PrecisionErrorZeroRange.Set(1e-5m);
    var a = "x + 1".Eval();
    MathS.Settings.PrecisionErrorZeroRange.Unset();
}
static void Main(string[] _)
{
    MathS.Settings.PrecisionErrorZeroRange.Set(1e-11m);

    // That's user-defined try, we can't control it
    try
    {
        DoSomething();
    }
    catch { }

    Console.WriteLine(MathS.Settings.PrecisionErrorZeroRange.Value);

    MathS.Settings.PrecisionErrorZeroRange.Unset();
}
```
The output will be 1e-5 instead of expected 1e-11 (because one unset was not called). That might be a bigger problem if we have set-unset instructions inside AM's functions (for example, Solvers use it to reduce precision and then raise it back).

**Solutions**

- To keep it as it is (then you *must* unset everything in catch)
- With "using" directive make settings available inside one scope (then you *must* use the "using" directive)

Maybe there're better options?

**Comment by Happypig375** [comment]
A `using` statement would be the idiomatic way to do this. To enforce this, you can write a custom Roslyn analyzer.

**Comment by WhiteBlackGoose** [comment]
We're probably going to do it via delegates, for example
```cs
MathS.Settings.Precision.As(100, () =>
{
  // some code considering precision = 100
});
```
Thanks to Zachary Patten for the advice
