### ISSUE TITLE
Polynomial division is broken

### ISSUE THREAD

**Issue by MomoDeve** [asc-community/AngouriMath#146]
after introducing EDecimal as floating point number, polynomial division can no longer properly divide entities because of precision loss. (see [TreeDivision.cs](https://github.com/asc-community/AngouriMath/blob/master/AngouriMath/Core/TreeAnalysis/Division/RationalDiv/TreeDivision.cs)). You can test it on such case: 
```cs
// should be simplified to x + y
Console.WriteLine("(x^2+2x*y+y^2)/(x+y)".Simplify());
```

**Comment by WhiteBlackGoose** [comment]
Hmm, please check **entities** branch, for some reason it works just fine on my machine. Maybe thanks to @Happypig375 's default downcast precision increased?

**Comment by MomoDeve** [comment]
Yes, seems like it was magically resolved. I think we should add a bit more tests on polynome division and then mark this issue as resolved after merging entity branch to master
