### ISSUE TITLE
AngouriMath cannot be run in parallel.

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#151]
All the code that changes static settings will cause conflicts between threads when AngouriMath is run in parallel. This is important because fixing this enables unit tests to be run in parallel which speeds up the development cycle.

**Comment by MomoDeve** [comment]
We are aware of that. @WhiteBlackGoose is thinking of new syntax for settings, which will be applied locally without altering global state

**Comment by WhiteBlackGoose** [comment]
Alright, I fixed it, but it needs further testing, so I'm not closing the issue. New syntax:
```cs
MathS.Settings.MaxExpansionTermCount.As(27, () =>
{
  // your code considering MaxExpansionTermCount = 27
});
```
Or
```cs
var roots = MathS.Settings.MaxExpansionTermCount.As(27, () =>
{
  return "x + 2".SolveEquation("x");
});
```

**Comment by WhiteBlackGoose** [comment]
Even without tests I realized that I missed the main point of that. I don't catch exceptions. Will soon fix it

**Comment by WhiteBlackGoose** [comment]
Is it possible to rethrow an exception if it was thrown and do nothing otherwise? Okay, I'll check

**Comment by Happypig375** [comment]
I mean you can combine the rethrowing `catch` with the code after the `try` block into a `finally` to deduplicate code.

**Comment by WhiteBlackGoose** [comment]
Sounds tested enough
