### ISSUE TITLE
Tensors for AngouriMath?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#152]
At some point I implemented a basic approach for class Tensor. However, I didn't work on that too much, while there are many methods yet to be implemented.

So far I didn't find any Tensor implementation that fits the following requirements:
1. Expandable to N-d Tensors (not only matrices)
2. Are Generic with T as a custom class (so we could use Entity as a Tensor's cell)
3. Have not only cross, dot, and piecewise products, but also allow to find determinent and be inverted
4. Transposition operation which works for O(1) (so that we don't work with elements, only with axes)
5. Reducing to M-d Tensors costs O(1) (for example, if we have a 4-d tensor t, t[2, 3] will return a 2-d tensor (matrix) for O(1) sharing the same data array)

The closest library I could find so far is [Towel](https://github.com/ZacharyPatten/Towel).

Now we need to decide which lib should be used & extended OR whether we need our own Tensor library. Any advice is welcomed!

**Comment by Happypig375** [comment]
While (3) is pretty standard, other requirements are really specific and hard to find an implementation meeting them.

(1) is usually not implemented because most uses of tensors in computing are related to graphics and simple physics where higher-dimensional tensors above vectors and matrices are not needed.

(2) is usually not implemented as well because the uses aforementioned require raw speed and low memory consumption so specialized types are usually used.

(4) is usually not implemented because that complicates the implementation that are not needed as mentioned above.

(5) is in direct conflict with mutability which most vector and matrix implementations have for speed. Sharing the same data while allowing mutability just causes bugs and data leakage.

To conclude, I don't think we can find a better library than Towel as mentioned above.

**Comment by WhiteBlackGoose** [comment]
What do you mean transposition (4) not needed? It's quite a basic operation with tensors and matrices. For example, you solved a system of equations and need all roots for X. The right way:
```
roots.Transpose(0, 1)[0]
// returns vector, so that (5) is also required
```
(2) And we need generic type we need because our tensor's cell is Entity, which is not a built-in type

**Comment by Happypig375** [comment]
>What do you mean transposition (4) not needed?

Transposition itself is standard but they are usually not O(1).
>(2) And we need generic type we need because our tensor's cell is Entity, which is not a built-in type

I merely explained why it is hard to find a library supporting this.

**Comment by WhiteBlackGoose** [comment]
I added some info to my comment.

Transposition might be not for O(1), but I don't see why we can't do it such. What are the limitations to do it for O(1)? It works so in PyTorch, for example, and NumPy

**Comment by WhiteBlackGoose** [comment]
Even if I will use Towel for matrices, I will also have to make Transposition constant method. It only swaps axes, and in any scenario I don't see how it might be a problem

**Comment by Happypig375** [comment]
Python is a dynamic language so variable types are nonexistent. (2) is implicitly true. For Python variables, you can swap 1D arrays for 2D arrays and vice versa. For C# to do this, you have to lose speed and sacrifice type safety.

**Comment by WhiteBlackGoose** [comment]
I meant that Transpose works for O(1) in PyTorch and Numpy.

We don't need different types for matrices and vectors, so that IsVector => Dimensions.Count == 1, IsMatrix => Dimensions.Count == 2.
And what do you mean lose speed? Where exactly? Say, 1-3ns on if check, especially if we inline it. Considering that we don't have types in this case so that Vector, Matrix are all Tensors with different dimensions, you should explain where we really lose performance

**Comment by Happypig375** [comment]
I am talking about why existing vector/matrix libraries will not meet the requirements. You are free to start anew.

**Comment by WhiteBlackGoose** [comment]
Arh, I see. I think it'd be pretty cool to make one so that it implements Tensors and, at the same time, works faster (no extra copying like in many matrices libs). But I'm still thinking about it. You made me doubt that in most cases people don't need tensors and will be fine with matrices. So, thanks for the advices, I will think.

**Comment by Happypig375** [comment]
For no-copying tensor reduction, you can reference https://www.nuget.org/packages/System.Memory/ for `System.Span` and `System.ReadOnlySpan`. For .NET Standard <=2.0, it is a backwards-compatible implementation that is a teeny tiny bit slower than the implementation on .NET Standard >=2.1. https://adamsitnik.com/Span/#slow-vs-fast-span
