### ISSUE TITLE
RationalNumber.FindRational(4.41m, MathS.Settings.FloatToRationalIterCount) fails to find a rational

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#156]
Maybe we should set default FloatToRationalIterCount to 15 (from the single-argument overload of FindRational) instead of 5.

**Comment by Happypig375** [comment]
@WhiteBlackGoose Something as simple as `(21/10)^2` cannot appear as a fraction. This is very unexpected.

**Comment by Happypig375** [comment]
@WhiteBlackGoose Will it be okay to increase this number?

**Comment by WhiteBlackGoose** [comment]
I don't think that's an issue, but you can increase it.

**Comment by Happypig375** [comment]
I mean by default.

**Comment by WhiteBlackGoose** [comment]
I know
