### ISSUE TITLE
Cannot be simplified

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#165]
From #164
```
MathS.FromString("1+2x*-1+2x*2+x^2+2x+2x*-4+2x*4+2x*2x*-1+2x*2x*2+2x*x^2+x^2+x^2*-4+x^2*4+x^2*2*x*-1+x^2*2x*2+x^2*x^2").Simplify()
```

**Comment by WhiteBlackGoose** [comment]
Fixed, I'll probably release 1.1.0.5 soon

**Comment by WhiteBlackGoose** [comment]
Oof I just realized: I added polynomial parser to Simplify, but there're cases that it won't work. First, if there should be a replacement. Second, when some terms are not polynomial, e. g. 2x + 3x + ... + 10x + e ^ x

**Comment by WhiteBlackGoose** [comment]
Continuation: #185
