### ISSUE TITLE
Operators for tensors?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#168]
Alright, recently AngouriMath has moved to new [Generic Tensor](https://github.com/WhiteBlackGoose/GenericTensor) library. Now we can use many more functions, such as slicing, subtensor, determinants, matrix inversion, and so on. But we need to distrubute functions over operators, and that is where I need some opinions. So we actually need to fill this table:

|          | Vector   | Matrix   | Tensor   |
|:--------:|:--------:|:--------:|:--------:|
| +        |          |          |          |
| -        |          |          |          |
| *        |          |          |          |
| /        |          |          |          |
| ^        |          |          |          |

Where each cell is responsible for operations.

For example, my draft:

|          | Vector        | Matrix         | Tensor    |
|:--------:|:-------------:|:--------------:|:---------:|
| +        | Concatenation | Piecewise      | Piecewise |
| -        | Piecewise     | Piecewise      | Piecewise |
| *        | Dot product   | Multiplication | Piecewise |
| /        | ????          | Division       | Piecewise |
| ^        | -             | Pwower         | Piecewise |

But I am not a big fan of it.

Or maybe we do not need different operators for different shapes?

**Comment by Happypig375** [comment]
>Alright, recently AngouriMath has moved to new Generic Tensor library. 

In the initial stage, I'd say that the Generic Tensor code should live in this repo until it matures.
>For example, my draft:

Suggestion:

<br/>|Vector | Matrix | Tensor
-|-|-|-
\+ | [__*Piecewise*__](https://mathworld.wolfram.com/VectorAddition.html) | Piecewise | Piecewise
\- | Piecewise | Piecewise | Piecewise
\* | [__*Cross product*__](https://math.stackexchange.com/a/246607/627798) | Multiplication | __*[Generalized cross product](https://en.wikipedia.org/wiki/Cross_product#Multilinear_algebra)*__
/ | [__*(Undefinable)*__](https://physics.stackexchange.com/a/111668) | Division | __*(Better not define if consistent definition not found)*__
^ | __*(n-times cross product)*__ | Pwower _(wow)_ | __*(n-times cross product)*__
% | __*Dot product*__ | __*Dot product*__ | __*Dot product*__
& | __*Concatenation*__ | |

**Comment by WhiteBlackGoose** [comment]
> In the initial stage the Generic Tensor code should live in this repo until it matures.

No real need. It's an independent project that can be used anywhere else.

The problem with cross product is just we don't need it as often as dot product. 
And we don't have % and & (as subnodes). We might want to add functions in the future.

Can functions exist without necessarily being a subnode? We could add operations like concatenation separately from Entity, so that they (those operations) are performed immediately, and not stored like children of an OperatorEntity

**Comment by Happypig375** [comment]
>No real need. It's an independent project that can be used anywhere else.

Multiple packages can have the same source repository. See .NET Core source repository.
>The problem with cross product is just we don't need it as often as dot product.

It is the mathematically more suitable operator where a vector is returned from two vectors like other numeric forms, not related to frequency of use which you can't prove anyways.
>And we don't have % and & (as subnodes). We might want to add functions in the future.

You can't really define the remainder and boolean AND operators for tensors.
>Can functions exist without necessarily being a subnode? We could add operations like concatenation separately from Entity, so that they (those operations) are performed immediately, and not stored like children of an OperatorEntity

How can you store `concat(A-B, C)` where A, B, C are matrix variables?

**Comment by WhiteBlackGoose** [comment]
> Multiple packages can have the same source repository. See .NET Core source repository.

Then why would I need the same repo at all? I can create a new repo with a separate readme, separate issues, etc.

> You can't really define the remainder and boolean AND operators for tensors without being inconsistent with * and /.

You mean that if we define & and % they won't make sense for other types of nodes? Yes, that's an issue, I'm thinking about it. Hope it's not a big problem

> How can you store concat(A-B, C) where A, B, C are matrix variables?

With defining a concat subnode (theoretically)

**Comment by WhiteBlackGoose** [comment]
The problem with cross product is also that I haven't implemented it for N-dimensional vectors yet

**Comment by WhiteBlackGoose** [comment]
My suggestion: we make all the operators for any kind of tensor piecewise. Then there will be no ambiguousness. If you, however, need some other kind of operations, they will be performed automatically (for example, `Tensor.MatrixMultiply(a, b)` will return a matrix, not a tree of two matrices)

**Comment by Happypig375** [comment]
#105 will still be implemented, right?

**Comment by MomoDeve** [comment]
I am not math expert, wtf is **n times cross product** and **pwower**?

**Comment by Happypig375** [comment]
My "n times cross product" means "performing the cross product n times".
Not sure about @WhiteBlackGoose's "pwower" though. :trollface:

**Comment by MomoDeve** [comment]
Whats the point of performing cross product n times? What kind of vector will it produce and what are the use cases?

**Comment by Happypig375** [comment]
Hmmm. I probably confused it with the matrix product on single-row/single-column matrices.

We can try to implement https://www.quora.com/Can-we-have-an-exponential-of-a-vector-like-exp-A-where-A-is-a-row-vector?share=1 though.

**Comment by WhiteBlackGoose** [comment]
I guess such a set of operators will be so unobvious for the user, that they will have to read documentation to get how it works. We can implement it as `MathS.Matrices.WhateverFunctionYouWant` (or maybe `MathS.LinearAlgebra.Whatever`), but so far I'm struggling, mb piecewise operations for all kinds will be better? If you need something else, you explicitly call it

**Comment by Happypig375** [comment]
Or maybe not have any operators at all - use methods instead.

**Comment by WhiteBlackGoose** [comment]
That's how it works in GenericTensor :)

**Comment by MomoDeve** [comment]
|          | Vector   | Matrix   | Tensor   |
|:--------:|:--------:|:--------:|:--------:|
| +        |   piecewise       |     piecewise     |    piecewise      |
| -        |   piecewise       |   piecewise       |   piecewise       |
| *        |     dot product     |   multiplication       |    -      |
| /        |     -     |     division     |       -   |
| ^        |    cross product      |      power    |      -    |

My thoughts:
- `+` for vector must be piecewise, so `v + u - u = v`
- as matrix multiplication can be written in terms of dot product of its rows/columns, I suggest `*` to mean dot product for vectors
- most operations for tensors should be explict functions as they behave quite different (tensor product for 1-component tensors (vectors) does not mean the same as vector dot product) .

**Comment by Happypig375** [comment]
I don't think C# operators can represent cross and dot products nicely. Matrix multiplication produces matrices but vector dot product produces scalars (not tensors). Using ^ to mean both cross product and power also is inconsistent. Making dedicated cross and dot functions seem the best way to go - #105.

**Comment by Happypig375** [comment]
Let's think this way - what would you interpret two vector variables written together without cross or dot operators? It is ambiguous - we cannot simplify it.

**Comment by WhiteBlackGoose** [comment]
"Promoting" vectors to matrices, I guess, is stacking for one, and stacking and transposition for another one. But I don't know if we need such a complex thing. I think we will keep them all piecewise, but I also keep the issue open

**Comment by Happypig375** [comment]
I have just come across https://github.com/dotnet/runtime/issues/28731 which suggests cross products for 2D and 4D vectors

**Comment by WhiteBlackGoose** [comment]
In AM we probably aren't going to do any operations that aren't implmeneted in GT, so it'd be better to move it to GT's same issue. And... well, since cross product sucks, in GT we might at some point **remove it** and replace with an algorithm for computing normal. Or leave it with something like "CrossProduct3D".

**Comment by WhiteBlackGoose** [comment]
It's been decided (see what's new in 1.3)
