### ISSUE TITLE
Can we merge OperatorEntity and FunctionEntity?

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#172]
From https://en.wikipedia.org/wiki/Operation_(mathematics),
>In mathematics, an operation is a function which takes zero or more input values (called operands) to a well-defined output value.[1] The number of operands is the arity of the operation. The most commonly studied operations are binary operations (i.e., operations of arity 2), such as addition and multiplication, and unary operations (i.e., operations of arity 1), such as additive inverse and multiplicative inverse.

All operators are functions. Why do we have two kinds of entities?

**Comment by WhiteBlackGoose** [comment]
I guess due to the difference of their syntax. I think we can merge them, but not now

**Comment by Happypig375** [comment]
Factorial is implemented with a `FunctionEntity` and does not seem to affect the syntax at all.

**Comment by WhiteBlackGoose** [comment]
Seems like it's not an issue anymore (although I might want to inherit former operators from Function)
