### ISSUE TITLE
ln(x, y, z, ...) is parsed successfully instead of throwing exception

### ISSUE THREAD

**Issue by MomoDeve** [asc-community/AngouriMath#175]
The following expression
```cs
Console.WriteLine(MathS.FromString("ln(x, y)"));
```
prints `log(e, x)` instead of throwing parser error

**Comment by WhiteBlackGoose** [comment]
Not only that, if you write wrong number of arguments, it won't throw exceptions

**Comment by WhiteBlackGoose** [comment]
Fixed, thanks
