### ISSUE TITLE
Should we really allow square brackets to represent round brackets?

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#181]
In https://github.com/davidedc/Algebrite, square brackets denote vectors/matrices/tensors. e.g. `1` is a scalar, `[1]` is a vector containing `1`, `[[1]]` is a matrix containing `1`... etc. Using square brackets for that purpose seems much more productive than interchange them with round brackets.

**Comment by WhiteBlackGoose** [comment]
It's a common mathematical convention that we could use [] as (), but mb we will change it in the future

**Comment by MomoDeve** [comment]
If we want to support parsing matrices/vectors from strings, its better to reserve `[ ]` for such operations and do not add ambiguity

**Comment by WhiteBlackGoose** [comment]
Yeah, so there's no need to support them as synonyms for the parser, especially considering that we will soon put them into practice for tensors
