### ISSUE TITLE
sin(2*x + 1) + cos(x - 1) + a cannot be solved

### ISSUE THREAD

**Issue by MomoDeve** [asc-community/AngouriMath#188]
but `sin(2*x + 1) + cos(x + 1) + a` can. Seems like it does not match patterns in TrigLinearSolver

**Comment by WhiteBlackGoose** [comment]
Alright, we gotta add the polynomial parser for sine and cosine function in the first place. I guess it helps
- [ ] To find all variable-containing sines and cosines
- [ ] Figure out which equations to refuse to solve (e. g. sin(sin(x)) + cos(x + a) is bad) via parsing linear children (I guess)
- [ ] Check if the polynomials fit the requirement of being linear and the ratio of their first coefficient is either 1 or 2 (e. g. 2x + a and x + b are okay, but 3x + a and x is bad, 3x : x = 3)
- [ ] Solve it

**Comment by WhiteBlackGoose** [comment]
#218 is about it

**Comment by MomoDeve** [comment]
fixed in [integration branch](https://github.com/asc-community/AngouriMath/pull/229/commits/141c7e6efcac2ebc3e2e88c625fc8a42b802448e)
