### ISSUE TITLE
FastExpression into linq expression

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#191]
- [ ] `Complex` -> `Complex`
- [ ] FastExpression to work for `ComplexNumber` instead of `Complex`

**Comment by MomoDeve** [comment]
Will FastExpression still be fast as it is if we switch from Complex to ComplexNumber?

**Comment by WhiteBlackGoose** [comment]
No, surely not as fast as for Complex

**Comment by MomoDeve** [comment]
I thought we point of fast expression was to get numeric result as fast as possible with saving at least double precision

**Comment by WhiteBlackGoose** [comment]
That's what we're going to implement compilation into delegates for. So that we compile a delegate which accepts and returns `Complex`, it will be even faster than the current `FastExpression`
