### ISSUE TITLE
Compile boolean expressions

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#208]
For the sake of consistency, we must support compilation to a `bool` as well as to a `Complex`

**Comment by Happypig375** [comment]
What about compilation to a Tensor or HashSet<double>?

**Comment by WhiteBlackGoose** [comment]
I... don't think we need it. Since `Tensor` just unites a couple of expressions into a table, you can compile them separately and then run. Same about `HashSet`
