### ISSUE TITLE
Assembly Strong-Name Signing

### ISSUE THREAD

**Issue by thomasgassmann** [asc-community/AngouriMath#221]
We're trying to use `AngouriMath` in an environment, where we need strongly-named assemblies.
Are there any plans to strongly-name the package published on NuGet?

**Comment by WhiteBlackGoose** [comment]
I think we can do it for the next release, thank you for your proposal

**Comment by WhiteBlackGoose** [comment]
@thomasgassmann hello. If you still consider using AngouriMath, we published a preview version here: https://www.nuget.org/packages/AngouriMath/1.2.0-preview.1

If something goes wrong, please, let me know.

**Comment by thomasgassmann** [comment]
@WhiteBlackGoose Thank you!
