### ISSUE TITLE
Keep irrational numbers and fractions until Eval is called

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#25]
So that symbolic computation, e.g. log(5, 3) + log(25, 3) Simplify-> 3 * log(5, 3) can be supported.

**Comment by Happypig375** [comment]
Adding fractions to this list. Rounding errors accumulate really fast.

**Comment by MomoDeve** [comment]
>Adding fractions to this list
We have already thought about that, but as floating point numbers are scattered around whole codebase and adding rational/irrational numbers requires rewritting whole Number abstraction. It is not very easy to implement, but will definitely be done at some point.
