### ISSUE TITLE
Differentiation etc. as Entities

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#26]
Differentiation can appear inside other math operations in normal mathematics. This should be supported.

**Comment by MomoDeve** [comment]
> Differentiation can appear inside other math operations in normal mathematics. This should be supported.

It is highly related to differential equations, so firstly we need to add integral support (expression, solver, simplifier and etc). If you just need an expression with derivative as a part, you can combine two expressions together

**Comment by WhiteBlackGoose** [comment]
- [x] Derivative
- [ ] Integral
- [ ] Limit

**Comment by WhiteBlackGoose** [comment]
Somehow works
