### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#27]
Add limits

**Comment by MomoDeve** [comment]
Started working on them! [limits branch](https://github.com/asc-community/AngouriMath/tree/limits) is available for testing (I am currently working on limit solving, so Entity nodes are not yet supported). Some cases are already working:
```cs
// lim(x -> 1+) (x^2 - 2) / (x - 1)
 Limit.ComputeLimit("(x^2 - 2) / (x - 1)", "x", 1, ApproachFrom.Left); // +oo

// lim(x -> +oo) (a*x + 1)/(x^2 - b)
 Limit.ComputeLimit("(a*x + 1)/(x^2 - b)", "x", RealNumber.PositiveInfinity, ApproachFrom.Left); // 0

// lim(x -> a-) 1 / (x - a)
var limit = Limit.ComputeLimit("1 / (x - a)", "x", "a", ApproachFrom.Left); // -oo
```
For infinities `ApproachFrom.Left/Right` does not matter. ComplexNumbers are not supported as approach points, so using them will throw an exception. If no limit was found, null is returned. Right now I am working on polynom divisions, later will probably add L'Hôpital rule and stuff from here: [list of limits](https://en.wikipedia.org/wiki/List_of_limits)

**Comment by WhiteBlackGoose** [comment]
1.1.0.4 once Limits done

**Comment by MomoDeve** [comment]
Should we left this issue until the limits are under work or close it for now? Seems like limits are already in master branch
