### ISSUE TITLE
Greek/Unicode characters as variable names

### ISSUE THREAD

**Issue by yoshiask** [asc-community/AngouriMath#293]
For example, `MathS.Var(θ)` throws a parse exception because of an unrecognized token. Even if Unicode characters aren't fully supported, it should at least allow Greek characters to be passed in and used as variables.

**Comment by WhiteBlackGoose** [comment]
Sounds useful. If you want, you may PR it, or just wait until we implement it

**Comment by WhiteBlackGoose** [comment]
Done
