### ISSUE TITLE
Vector entity

### ISSUE THREAD

**Issue by yoshiask** [asc-community/AngouriMath#305]
An `Entity.Vector` would be pretty simple to implement. It basically holds an array of `Entity`s that represents the components, and adds a few extra methods for things like cross/dot products and unit vectors along with operator overloads.

I have already written my own class that internally uses `Entity`s for components, but the class itself is not an `Entity` so I don't know what additional work might have to be done.

**Comment by WhiteBlackGoose** [comment]
We already have `Entity.Tensor`, which could be a vector, matrix, or a more dimensional tensor

**Comment by yoshiask** [comment]
Oh, right, I forgot about that. It's still missing methods that are useful for vectors, like `GetLength()`, `Normalize()`, `GetAngleWithAxis(int axis)`. If tensors are already available though, I can see how such functionality might not align with the primary purpose of the library.

**Comment by WhiteBlackGoose** [comment]
There's Shape instead of GetLength() though. Normalize might be useful, but don't forget, it's a symbolic library, so it will just return the same vector with each node represented as `a / (a2 + b2 + c2...)`, you get the point

**Comment by WhiteBlackGoose** [comment]
Although maybe it's more convenient to have matrix and vector inherited from tensor? Or all the three from Entity? Maybe

**Comment by WhiteBlackGoose** [comment]
So I've decided to make it a one-column matrix, as no other idea came up
