### ISSUE TITLE
Please add the ability to change the right side of an equation.

### ISSUE THREAD

**Issue by Ranodj** [asc-community/AngouriMath#313]
Right now it defaults the right side of the equation to 0, but I need it to solve equations like  3x + 4 = 5 * y. Maybe allow one to replace the zero in the equation through some seperate command like equation.Replace(0, 6) or something like that. Also if you could add this to systems of equations that would be extremely useful too.

**Comment by WhiteBlackGoose** [comment]
Hi. You can try writing
```cs
Entity equation = "2x + 3 = 5";
Console.WriteLine(equation.Solve("x"));
```

Make sure you have the last version, which is 1.2.0-preview.5
