### ISSUE TITLE
C++ wrapper?

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#337]
Still sounds crazy, but maybe ideas come up. I was able to build it into a native code for win x64 so far (into an exe), so it's possible. The exe's size was 9Mb, quite a lot, but not so much.

**Comment by Happypig375** [comment]
Must be compared to existing offerings on the C++ side in order for this to be viable

**Comment by WhiteBlackGoose** [comment]
~~There's always room for AM~~ There are a few alternatives, some of which were abandoned 10 years ago, some even before. It would be fun to compete with those existing, even if there's a big boy I don't see yet.

**Comment by Happypig375** [comment]
Here: https://github.com/symengine/symengine
