### ISSUE TITLE
Add upcasts to subtrees when compiling

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#340]
Say, I have this
```cs
Entity expr = "x + y";
var func = expr.Compile<double, float, double>("x", "y");
func(3, 4);
```
It won't compile because you can't add a double to a float without upcasting float to double. So, when compiling, we just need `MaxType(Type left, Type right)` thing to choose the right type and upcast both operands to it.

**Comment by KaranChadha10** [comment]
the hierarchy is float < double so you have to add f at the end of 4
func(3,4f)

**Comment by WhiteBlackGoose** [comment]
@KaranChadha10 sorry, didn't notice your comment. The hierarchy is [here](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/Functions/Compilation/IntoLinq/DefaultConverters.cs#L53). Yes, float gets casted into double.

But `func`'s type is `Func<double, float, double>`, so I see no point in writing the arguments as `3.0, 4.0f`, as they will be converted into a double and a float automatically
