### ISSUE TITLE
Entity.SolveEquation function cannot solve an equation that has equal sign

### ISSUE THREAD

**Issue by KuhakuPixel** [asc-community/AngouriMath#343]
`
Entity expr = "x+8=4";
Console.WriteLine(expr.SolveEquation("x"));
`

according to the  algebra section example inside the readme.md it seems that you need to simplify the equation until the right side is 0 

So people need to simplify the equation to 
`
Entity expr = "x+4";
`
in order for the program to work ,it would be really nice if the function can automatically solve x if there is "=" in the equation

**Comment by WhiteBlackGoose** [comment]
There's `Solve` for it. `SolveEquation` is made exactly for cases when we have an equation of the form `f(x) = 0`. But you can write
```cs
Entity expr = "x + 8 = 4";
Console.WriteLine(expr.Solve("x"));
>>> { -4 }
```

Or even more complicated

```cs
Entity expr = "x2 = 16 and x < 0";
Console.WriteLine(expr.Solve("x"));
>>> { -4 }
```

**Comment by Happypig375** [comment]
Should rename it to `SolveEqual0`?

**Comment by WhiteBlackGoose** [comment]
I better make the docs more clear

**Comment by Happypig375** [comment]
Clear name is better than docs

**Comment by WhiteBlackGoose** [comment]
Fixed the docs. Feel free to ask other questions, if they appear.
