### ISSUE TITLE
How to multiply Matrix and Vector?

### ISSUE THREAD

**Issue by andrew-boyarshin** [asc-community/AngouriMath#344]
```cs
var bArray = new Entity[size];
Array.Fill(bArray, Entity.Number.Integer.One);

var bVector = MathS.Matrices.Vector(bArray);

for (int i = 0; i < 10000; i++)
{
    var product = MathS.Matrices.ScalarProduct(bVector, bVector);
    var normedVector = (bVector / MathS.Sqrt(product)).EvalTensor();
    var vector =  MatrixVectorMultiplication(tensor, normedVector);
    bVector = vector;
}
```

I see no way to implement `MatrixVectorMultiplication` (`N*M x M*1 = N*1`), except for manual row iteration and dot products. I tried overriden `operator*` and `TensorVectorDotProduct`, both are inapplicable (unless I create a copy of the vector as matrix with 1 column). I'd expect both GenericTensor and AngouriMath to support such basic operation.

**Comment by WhiteBlackGoose** [comment]
You might want to create a 1-column matrix instead of a vector, I think.  Here's what I mean:
```cs
var mat1 = MathS.Matrices.Matrix(new Entity[,]
{
    { "a", "b", "c" },
    { "d", "e", "f" },
    { "g", "h", "k" }
}
);

var mat2 = MathS.Matrices.Matrix(new Entity[,]
{
    { "A" },
    { "B" },
    { "C" },
}
);

var res = MathS.Matrices.MatrixMultiplication(mat1, mat2);

WriteLine(res);
```

The output:
```
Matrix[3 x 1]
0 + a * A + b * B + c * C
0 + d * A + e * B + f * C
0 + g * A + h * B + k * C
```

**Comment by andrew-boyarshin** [comment]
@WhiteBlackGoose yeah, But then I can't use `VectorDotProduct`. It's basically the question of what I want to reimplement. I copy-pasted `Multiply`, removed access to `b.Shape[1]`, `b.block[1]` and inlined `y = 0`, this worked for me. Still it would be better to have that in AngouriMath out-of-box.

**Comment by WhiteBlackGoose** [comment]
I see. I hope we will have it more conveniently implemented when we will have `Vector` and `Matrix` as separate nodes, which I'm planning to do for the next release

**Comment by WhiteBlackGoose** [comment]
@andrew-boyarshin you might be interested in taking part in a [discussion](https://github.com/asc-community/AngouriMath/discussions/345) about vectors/matrices and their behaviour

**Comment by WhiteBlackGoose** [comment]
Now you can create matrices and vectors in a more convenient way, as well as work with them. Say,
```cs
var m1 = MathS.Matrix(new Entity[,]
{
    { 1, 2 },
    { 3, 4 }
});
var v = MathS.Vector(0, 1);

var m2 = m1 * v; // performs a matrix multiplication
var len = MathS.Abs(m2).Evaled; // finds the length of a vector as square root of the sum of the squared values of the vector
```
To perform scalar product of two vectors, simply transpose one of them
```cs
var v1 = MathS.Vector(1, 2);
var v2 = MathS.Vector(3, 4);
var v3 = v1.T * v2;
Console.WriteLine(v3.InnerSimplified);
```

**Comment by WhiteBlackGoose** [comment]
In case you missed, the new version is published. Wiki for it is [here](https://github.com/asc-community/AngouriMath/wiki/10.-Matrices).
