### ISSUE TITLE
Status board of latest master

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#358]
It will reflect all stability checks, to be precise, whether
```
C#/F# builds on
  - Windows
  - Linux
  - MacOS
C++ builds on
  - Windows
  - Linux
  - MacOS
C#/F# tests pass on
  - Windows
  - Linux
  - MacOS
C++ tests pass on
  - Windows
  - Linux
  - MacOS
```
In total, 12 checks. It will be a `<details>` block in the readme (or on the website)

**Comment by Happypig375** [comment]
Might as well test C# on Linux and Mac as well.

**Comment by WhiteBlackGoose** [comment]
@Happypig375 idk if we need it. Unlike for C++, we have exactly the same SDK for C#. Let's see if someone recalls a difference which requires testing C# on Linux and OS X too.

**Comment by WhiteBlackGoose** [comment]
Actually, we can do it for consistency, and just in case if we do something non-cross-platform, we will get immediately notified. So okay, let's do it.

**Comment by WhiteBlackGoose** [comment]
Ah, no, it doesn't make any sense for C# and F# to be in one workflow. They also should be different. So there will be a matrix:
[Build, Test] x [C#, F#, C++] x [Windows, Linux, OS X]

**Comment by WhiteBlackGoose** [comment]
Hmmm, it seems like we can't create a badge for jobs separately. Then it will require some additional thinking
