### ISSUE TITLE
Piecewise integral

### ISSUE THREAD

**Issue by devel0** [asc-community/AngouriMath#359]
## description

piecewise doesn't forward integral into their components

## repro

```csharp
var a = "piecewise(2*t provided t<0, 4*t^3 provided t>=0)";            
var s = a.Integrate("t").Simplify();
System.Console.WriteLine(s);
```

## actual

```
integral((2 * t if t < 0, 4 * t ^ 3 if t >= 0), t)
```

<div align="center"><img style="background: white;" src="https://render.githubusercontent.com/render/math?math=%5Cint%20%5Cleft%5B%5Cbegin%7Bcases%7D2%20t%20%5C%3A%20%5Ctext%7Bfor%7D%20%5C%3A%20t%20%3C%200%5C%5C4%20%7Bt%7D%5E%7B3%7D%20%5C%3A%20%5Ctext%7Bfor%7D%20%5C%3A%20t%20%5Cgeqslant%200%5Cend%7Bcases%7D%5Cright%5D%20dt"></div>

## expected

```
piecewise(t ^ 2 provided t<0, t ^ 4 provided t>=0)
```

<div align="center"><img style="background: white;" src="https://render.githubusercontent.com/render/math?math=%5Cbegin%7Bcases%7D%7Bt%7D%5E%7B2%7D%20%5C%3A%20%5Ctext%7Bfor%7D%20%5C%3A%20t%20%3C%200%5C%5C%7Bt%7D%5E%7B4%7D%20%5C%3A%20%5Ctext%7Bfor%7D%20%5C%3A%20t%20%5Cgeqslant%200%5Cend%7Bcases%7D"></div>

## version
git: 8d16c32374962a5c5870df4ec491baca8d9529bc

**Comment by WhiteBlackGoose** [comment]
It's fixed in `master`. Will be available in 1.3 p3.
