### ISSUE TITLE
Improve F# wrapper functions

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#365]
- [ ] Other function names are nouns while greater/less are adjectives
- [ ] Rename interval functions, e.g. \`\`rightInclusive\`\` -> \`\`(-oo; ]\`\`
- [ ] Change matrix and vector functions to accept seqs instead of lists

**Comment by WhiteBlackGoose** [comment]
1) What could be a replacement for them? To me those sound fine, but if there's a better idea...
2) Agree
3) If implementable...

**Comment by Happypig375** [comment]
isGreater, isLess?

**Comment by WhiteBlackGoose** [comment]
And how are they nouns now? Also now they sound like active actions, instead of nodes. @Happypig375

**Comment by WhiteBlackGoose** [comment]
I'm now thinking, that ` ``(-oo; ]`` ` syntax would be inconsistent with those which take two arguments, unless we have something like ` ``[ ; )`` ` for those taking two arguments.

**Comment by WhiteBlackGoose** [comment]
Also, `vector` already accepts a sequence. Unlike matrix, though, but I think we don't need sequences for matrix (otherwise, provide a usecase where `matrix` should accept a sequence)

**Comment by WhiteBlackGoose** [comment]
`greater` and `less` remain, `vector` already accepts a `seq`, and I don't know if it's a good idea to rename intervals. If you want, you can add a couple of shortcuts to them (not as main functions)
