### ISSUE TITLE
Use IsExternalInit NuGet package to enable consumption in .NET 5.0 projects

### ISSUE THREAD

**Issue by andrew-boyarshin** [asc-community/AngouriMath#369]
See dotnet/roslyn#50696. Use <https://github.com/manuelroemer/IsExternalInit> from the author of <https://github.com/manuelroemer/Nullable> you already use to fix compilation issues on older compilers (such as the one in .NET 5.0 or 6.0p1 SDK). It does it right, `CSharpWorkarounds.cs` causes issues right now.

**Comment by WhiteBlackGoose** [comment]
Hmm. It actually should work fine:
- [Console sample .net 5](https://github.com/asc-community/AngouriMath/tree/master/Sources/Samples/SampleNet5)
- [Library targeting .net 5](https://github.com/WhiteBlackGoose/AngouriMath.Terminal/tree/main/AngouriMath.Terminal/AngouriMath.Terminal.Shared)
- [Library targeting standard 2.0](https://github.com/asc-community/AngouriMath/tree/master/Sources/Wrappers/AngouriMath.FSharp)

But I'll see if I'm able to reproduce the bug from the issue.

**Comment by WhiteBlackGoose** [comment]
Okay, let's see if we manage to do it by 1.3.

**Comment by WhiteBlackGoose** [comment]
@andrew-boyarshin okay, so I finally did it with this package. The next update will contain it (1.3-preview.5 or 1.3). If urgent, one can use version `0.0.0-master-1621715515-18e79ac`, adding the source beforehand:
```
https://www.myget.org/F/angourimath/api/v3/index.json
```
