### ISSUE TITLE
Module: `Numbers`

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#405]
**The package I want to suggest the idea to**: AngouriMath.FSharp

### Conversions
`asComplex`, `asReal`, `asRational`, `asInteger` (What to do when casting is impossible?).

### Functions
`re`, `im` for real and imaginary part of a complex number. It takes an `Entity` and inside applies `asComplex`.
`num`, `den` for numerator and denominator of a rational number. It takes an `Entity` and inside applies `asRational`.

**Comment by Happypig375** [comment]
Why don't just cast?

**Comment by WhiteBlackGoose** [comment]
Doesn't look nice, does it? Provided that you'd need to alias `Entity` or fully qualify `Entity.Number.Real`...

**Comment by Happypig375** [comment]
`type Real = Entity.Number.Real`

**Comment by WhiteBlackGoose** [comment]
It still would require the `downcast` thing, unless I'm missing something.

**Comment by Happypig375** [comment]
I can just write `:?> Real` instead of `|> asReal`.

**Comment by WhiteBlackGoose** [comment]
Got it. Okay, fair. Then there will be this alias in `Numbers`

**Comment by WhiteBlackGoose** [comment]
Bruh, now we have Honk#'s `Downcast<>`, so it becomes even more useless
