### ISSUE TITLE
Support the equality symbol and inequalities

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#41]
Currently, equations cannot be entities. Inputs like `x+y=z`, `x+y<z` and `x+y≤z` should be supported.

**Comment by MomoDeve** [comment]
We do not support inequalities solving for now. `=` is tricky, because entity with it cannot be part of other entity. I suggest replacing `A = B` with `A - (B)` as workaround

**Comment by WhiteBlackGoose** [comment]
There is no point in supporting them as Entities (even though we already support equations in MathS.Equations)

**Comment by WhiteBlackGoose** [comment]
Haha, funny how the tables turned
