### ISSUE TITLE
Tensoric power

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#413]
**The packages I want to suggest the idea to**: AngouriMath

### C#

~~API: `Matrix.TensoricPower(int)` or `Matrix.TensoricPower(Matrix, int)`? (should be static or not?)~~
API: `Matrix.TensorPower(int)`

**Comment by Happypig375** [comment]
Why not the normal power node?

**Comment by WhiteBlackGoose** [comment]
It's not a node, it's just an operator/method. And how are you going to distinguish "[[1, 2], [4, 5]]" if it's normal power or tensoric, if it was a node?
