### ISSUE TITLE
Some convenient API for Taylor series

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#449]
1. To add overloads which would assume that the old variable and the new one are the same
2. To add overloads which would assume that the point of differentiation is zero (Maclaurin series)

**Comment by ryyanmapes** [comment]
I think the best way to do this without bloating the code with repetitious permutations is to create a simple class that contains the variable, polynomial replacement variable, and starting point. The multivariable version would simply take in multiple of these objects. The new overloads would not be on the Taylor series functions, but on the creation of the parameter object. Does that sound okay?

**Comment by WhiteBlackGoose** [comment]
Mmmm... it sounds *ok*, but this would create unnecessary confusion with a new type. Hmmm... here's what I think:

1) The first method would be Maclaurin series which would assume that our old and new variables coincide (so it takes `params Variable[] variables` as an argument)
2) The second method would be Taylor series which would also make that assumption, so we get `params (Variable Var, Entity Coordinate)` as an argument
3) The third method will have `params CoordInfoType[] coords` (not sure how to call the type), and this time, it will contain those types (I guess it's a good idea to have a number of implicit operators for conversation to this type).

Justification: most of the time we need Maclaurin series, so we do need it as a separate method. Sometimes we want to specify coordinates other than 0, so we need the second method (but most often we want to preserve the vars the same). And finally, if we need something custom, we call the third method.

**Comment by ryyanmapes** [comment]
Because we already have four different Taylor series methods (two for single variable, two for multivariable), this means we'd have 12 separately documented methods total. It's easy to do, just a bit verbose. Maybe we should merge the single variable and multivariable methods because they are so similar? 
Also, looking at it again, a Builder pattern might work well here also? Not sure, lots of options.

**Comment by WhiteBlackGoose** [comment]
I think that it's enough to have the three methods I listed + an infinite generator which accepts the most general arguments. Here's an example of how they could be used:
```cs
MathS.Series.Maclaurin(expr, 3, "x")
MathS.Series.Maclaurin(expr, 3, "x", "y")
MathS.Series.Taylor(expr, 3, ("x", 0))
MathS.Series.Taylor(expr, 3, ("x", 0), ("y", 4), ("z", 7))
MathS.Series.Taylor(expr, 3, ("x", "t", 0), ("y", "s", 2), ("z", "u", 3))
MathS.Series.TaylorTerms(expr, ("x", "t", 0), ("y", "s", 2), ("z", "u", 3))  <-- the generator
```
