### ISSUE TITLE
Simplify a / b / c into a / (b * c)

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#47]
So that the LaTeX output can be `\frac{a}{b\times c}` instead of `\frac{\frac{a}{b}}{c}` which takes a lot of vertical space.

**Comment by WhiteBlackGoose** [comment]
a / b / c are equally complicated according to our algorithm. It is still hard to determine which expression is more complicated. We will improve our simplification algorithm, but we cannpt release some sort of hotfix now.

**Comment by Happypig375** [comment]
This simplification still does not happen yet.

**Comment by WhiteBlackGoose** [comment]
You can set your own criteria in MathS.Settings.ComplexityCriteria now (though I'd better do it a bit more convenient by exposing some system functions to the user, such as the one that counts nodes, but the concept will remain)

**Comment by Happypig375** [comment]
Wolfram Alpha, Mathway etc. all simplify a/b/c into a/(b*c). It is even what Math teachers say - nested fractions are never the most simple form.

**Comment by WhiteBlackGoose** [comment]
Okay, I will change the defaul complexity criteria

**Comment by WhiteBlackGoose** [comment]
Fixed
