### ISSUE TITLE
EvalBoolean returns true on NaN-compare

### ISSUE THREAD

**Issue by Sesa1988** [asc-community/AngouriMath#491]
**Steps to reproduce**

- Create following expression: "1 / 0 > 2"
- Evaluate boolean (expr.EvalBoolean())

**Result**
This returns true

**Expected Result**
NaN or an Exception should be returned

**Comment by WhiteBlackGoose** [comment]
The reason it happens is this line:
```cs
(Real reLeft, Real reRight) => reLeft > reRight,
```
there should be checks on NaN

Thanks for the report, I'll soon it fix

**Comment by WhiteBlackGoose** [comment]
Fixed, thanks for reporting! The fix will be available since 1.4.0-preview.2
