### ISSUE TITLE
Support min, max, mean, mode, median

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#52]
With symbolic results.

**Comment by WhiteBlackGoose** [comment]
The library works with complex numbers. How would you take min/max from that? Mean would work fine, we will add. We will also add abs() function.

**Comment by Happypig375** [comment]
If complex numbers are encountered, handle them just like how you would handle a division by zero.

**Comment by WhiteBlackGoose** [comment]
There's no strict difference between real and {complex but not real} numbers. They all are complex. Maybe we will implement them and, as you said, return NaN if some of them are not real. Not now, though.

**Comment by Happypig375** [comment]
>We will also add abs() function.

Tensors should be special-cased to evaluate its determinant.

**Comment by WhiteBlackGoose** [comment]
Wondering what would be the exact API for that... the only argument should be a vector?

**Comment by Happypig375** [comment]
https://en.wikipedia.org/wiki/Maxima_and_minima#In_relation_to_sets
The definition seems to use an ordered set. Vectors and matrices, being enumerable, could fit too.

**Comment by WhiteBlackGoose** [comment]
Moved [here](https://github.com/asc-community/AngouriMath/issues/321)
