### ISSUE TITLE
Integer division by default to be double

### ISSUE THREAD

**Issue by WhiteBlackGoose** [asc-community/AngouriMath#541]
In the compilation protocol the integer division should be upcasted to a double. For example, `1/9` should be `0.111111` instead of `0`.

**Comment by Happypig375** [comment]
What about complexes from sqrt(-1)

**Comment by WhiteBlackGoose** [comment]
Good question. I think I'm going to leave it as it is for now. If the user needs complex numbers, they can provide a protocol with a custom constant converter
