### ISSUE TITLE
Incorrect work of solving a system of equations

### ISSUE THREAD

**Issue by alex0alex0** [asc-community/AngouriMath#559]
The version I use-AngouriMath 1.3
If in the example of solving the system of equations

var system = Equations(
    "x2 + y",
    "y - x - 3"
);
Console.WriteLine(system.Solve("x", "y"));

expression "x2 + y" replace with "(x2 + y) / 2" 
an error occurs

Thanks.

**Comment by alex0alex0** [comment]
...or any expression with brackets.

**Comment by WhiteBlackGoose** [comment]
@alex0alex0 thanks for the reporting! Seems like `Solve` returns null on such a simple equation. 

> ...or any expression with brackets.

Can you give more examples, please?

**Comment by WhiteBlackGoose** [comment]
Hope it will be fixed today

![image](https://user-images.githubusercontent.com/31178401/151335541-a1e309a8-8cba-4fcb-a8ae-7db066ce3e00.png)

**Comment by WhiteBlackGoose** [comment]
Ok so, the example from the issue fixed. See [**here**](https://am.angouri.org/quickstart/#dotnet) how you can get the latest version of AngouriMath (from the master branch. It's pushed to myget feed).

Let me know if there are other related examples

**Comment by alex0alex0** [comment]
Thank you. I can try in a couple of days.
