### ISSUE TITLE
Trigonometric issue

### ISSUE THREAD

**Issue by CosminCAS123** [asc-community/AngouriMath#568]
**The version I use** :Angouri 1.3.0 

**Unexpected behaviour or bug**: Both Simplify() and evaled give NaN for tan(pi).However , if you type sin(pi)/cos(pi) it will give the correct answer, 0.

**Comment by WhiteBlackGoose** [comment]
Thanks for the report. Should be fixed now. To get the latest/nightly build of AngouriMath, do the following.

```
dotnet new nugetconfig
dotnet nuget add source https://www.myget.org/F/angourimath/api/v3/index.json
dotnet remove package AngouriMath
dotnet add package AngouriMath -v 0.0.0-master-1655993650-43fbfb2
```

It will get you the latest (on `master` branch) package.
