### ISSUE TITLE
Variable with number in name

### ISSUE THREAD

**Issue by Angelo50** [asc-community/AngouriMath#579]
Hi, First, Great job
Simple question, Is it possible to use entity name with number in as follow
I mean:
If I execute the following:

            Entity expr = "2 + 3";
            Entity expr2 = "2 + 3 + R3";
            Console.WriteLine(expr2.Evaled);

Then  the result is : 
**5 + R ^ 3**

I would like to have
**5 + R3**

Can you help ?

Thanks

**Comment by WhiteBlackGoose** [comment]
Hi!

You can't do `R3`, but you can do `R_3`:
![image](https://user-images.githubusercontent.com/31178401/178217368-76a3cbd0-5540-4bf3-93a6-c232ef2f41be.png)

**Comment by Angelo50** [comment]
Thanks a lot :)

**Comment by Angelo50** [comment]
:)
