### ISSUE TITLE
is there a way to stop the evaluation of the  a string while using .Latexise() function 

### ISSUE THREAD

**Issue by TheOOnewbie** [asc-community/AngouriMath#590]
I am trying to parse a string to Latex, while doing so any given numbers in the string are usually evaluated and turned into one long hard to read number, is there a way to stop that ?

**Comment by WhiteBlackGoose** [comment]
Hi, there's no evaluation on Latexise. Can you give an example / post code?
![image](https://user-images.githubusercontent.com/31178401/181230134-c7dbe6b5-5905-44a9-af0c-9c57342c52b6.png)

**Comment by TheOOnewbie** [comment]
Hi, sure, I will give you a simple one, "0.86 * (WV/190)^2".Latexise(); returns

 
![image](https://user-images.githubusercontent.com/107171977/181230927-6e2e23f7-c817-4c3d-b466-3f329bd72be6.png)


also for some reason, hyperbolic tan is dealt with in it´s exponential form and messing up the equation badly, 

![image](https://user-images.githubusercontent.com/107171977/181231132-cd53707e-d1c2-4cdb-855c-284778e5da24.png)

using this code "(0.578)/sqrt(tanh((3.68*Hf)/(D)))".Latexise() gives you what what is given above

**Comment by TheOOnewbie** [comment]
> Hi, sure, I will give you a simple one, "0.86 * (WV/190)^2".Latexise(); returns
> 
> ![image](https://user-images.githubusercontent.com/107171977/181230927-6e2e23f7-c817-4c3d-b466-3f329bd72be6.png)
> 
> also for some reason, hyperbolic tan is dealt with in it´s exponential form and messing up the equation badly,
> 
> ![image](https://user-images.githubusercontent.com/107171977/181231132-cd53707e-d1c2-4cdb-855c-284778e5da24.png)
> 
> using this code "(0.578)/sqrt(tanh((3.68*Hf)/(D)))".Latexise() gives you what what is given above

the only thing which could lead to such case is evaluating/simplifying the expressions at some point after calling Latexise() function

**Comment by WhiteBlackGoose** [comment]
Here's the result in my case for the first one:
![image](https://user-images.githubusercontent.com/31178401/181232453-e5448a66-eb08-4ff3-81ca-0fde2cf75597.png)

**Comment by WhiteBlackGoose** [comment]
> also for some reason, hyperbolic tan is dealt with in it´s exponential form and messing up the equation badly

Yeah, that's fair. The reason is because we don't have a separate entity for `tanh`, so it's just straight substituted, [like this](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Convenience/MathS.cs#L1405)

**Comment by TheOOnewbie** [comment]
Let me check my code, I will be back.

**Comment by TheOOnewbie** [comment]
Hi, "Ac * Wc".Latexise() for some reason doesn´t  show the multiplication sign, as for the upper problems it turned out that I used another library, my bad

![image](https://user-images.githubusercontent.com/107171977/181236330-867c6dd5-4bde-40c0-91b0-d8c2af72c85c.png)

"((PWS) * D * (H^2) )/ 2" is below
![image](https://user-images.githubusercontent.com/107171977/181236407-16da70e5-dee0-41c6-9d70-8dc7f822e985.png)

**Comment by TheOOnewbie** [comment]
is there a way to allow the parser to deal with certain characters as variables ?

the problem is => S1 is written as 
![image](https://user-images.githubusercontent.com/107171977/181238814-6633b4f2-ad7d-4c41-8a57-e2afa2a96946.png)

**Comment by WhiteBlackGoose** [comment]
> "Ac * Wc".Latexise() for some reason doesn´t show the multiplication sign

Yeah. The idea was to mimic math notation, where we also often omit it. I agree that it's ambiguous in this case, thanks for the report. 

> the problem is => Q * Fv * (S1) is written as

For subscript use `_`, like this:
![image](https://user-images.githubusercontent.com/31178401/181242726-2aacaaba-c388-4d5f-8259-bd82c72549b5.png)

**Comment by TheOOnewbie** [comment]
> > "Ac * Wc".Latexise() for some reason doesn´t show the multiplication sign
> 
> Yeah. The idea was to mimic math notation, where we also often omit it. I agree that it's ambiguous in this case, thanks for the report.
> 
> > the problem is => Q * Fv * (S1) is written as
> 
> For subscript use `_`, like this: ![image](https://user-images.githubusercontent.com/31178401/181242726-2aacaaba-c388-4d5f-8259-bd82c72549b5.png)

regarding the disappearance of the multiplication sign, is there a way to just turn it of ? or force it to always write it?

**Comment by WhiteBlackGoose** [comment]
I'm afraid, no. You can make a workaround the following way:
1. Create your own node instead of `Entity.Mulf`, e. g. `ExplicitMul` and inherit it from `Entity`
2. Using method `Replace` you can replace it with your node:
```cs
public Entity ReplaceMul(Entity expr) => expr switch
{
    Entity.Mulf(var a, var b) => new ExplicitMul(a, b),
    var other => other
};
...
var newExpr = expr.Replace(ReplaceMul);
```

And for your `ExplicitMul`, override method `Latexise` to always display the multiplication sign. Here's the current implementation of [Latexise for Entity.Mulf](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Functions/Output/Latex/Latex.Arithmetics.Classes.cs#L34)
