### ISSUE TITLE
supporting if, max and min statements

### ISSUE THREAD

**Issue by TheOOnewbie** [asc-community/AngouriMath#592]
**The package I want to suggest the idea to*AngouriMath*: 

is there a way to add IF, min and max statements into the words which should not be interpreted as variables ?

**Comment by WhiteBlackGoose** [comment]
There's [provided](https://am.angouri.org/docs/AngouriMath/MathS/Provided.html) and [piecewise](https://am.angouri.org/docs/AngouriMath/MathS/Piecewise.html) for if. Syntax:
```
a / b provided not (b = 0)
```
and
```
piecewise(a / b provided not (b = 0), a / 2 provided a > 0, -a)
```

As per min/max, no, we don't have them, but there's an [issue](https://github.com/asc-community/AngouriMath/issues/321) for it.
