### ISSUE TITLE
Simplify() question

### ISSUE THREAD

**Issue by pandrei1** [asc-community/AngouriMath#597]
Is there a way to simplify this expression?

Entity e = "(1/9 + 1 / 1.7522123893805313)*x";
var e1 = e.Simplify();
WriteLine(e1);

The output is "10.7522123893805313 * x / (1.7522123893805313 * 9)". This is correct, but I wished it was only a constant times x.

Thank you for your time. Great project!

**Comment by WhiteBlackGoose** [comment]
Hi! In simple cases you can use `e.Evaled`:

![image](https://user-images.githubusercontent.com/31178401/192144017-fbf449c6-4a3e-4f34-830d-75449aad773a.png)

You can also check out [this](https://am.angouri.org/docs/AngouriMath.MathS/Utils/TryGetPolyLinear.html) method if you need to extract the coefficient by a certain variable (it tries to represent your function as an n-power polynomial and retrieve coefficients for you)

**Comment by pandrei1** [comment]
I see.  However, the above expression is coming after a Simplify(). Here is a simple version of the code. The fist one works perfectly, however the second one (which is the one I have) does not work. Should I first convert to string and then parse and Entity and use .Evaled? 

Entity e = "(1/9 + 1 / 1.7522123893805313)*x";
WriteLine(e.Evaled);
WriteLine(e.Simplify().Evaled);

Thank you.

**Comment by WhiteBlackGoose** [comment]
No, just use the second version. Don't apply simplify, just use `Evaled`. I'm honestly not entirely sure why Simplify didn't work as expected there. I'm not at home right now, but you can check if `Alternate()` method returns a desired result
