### ISSUE TITLE
Use C# 8 nullable reference types

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#60]
Reference https://github.com/manuelroemer/Nullable.

**Comment by WhiteBlackGoose** [comment]
What's the point of using it?

**Comment by Happypig375** [comment]
Making clear whether parameters are nullable lets downstream users avoid unintentionally passing nulls into methods.

**Comment by Happypig375** [comment]
This is not done. Request reopen.

**Comment by Happypig375** [comment]
𝖳𝗁𝗂𝗌 𝗂𝗌 𝗇𝗈𝗍 𝖽𝗈𝗇𝖾. 𝖱𝖾𝗊𝗎𝖾𝗌𝗍 𝗋𝖾𝗈𝗉𝖾𝗇.

**Comment by MomoDeve** [comment]
Could you at least put examples where this feature can be used in our library. From my experience, almost always methods parameters must not be null in AM

**Comment by Happypig375** [comment]
>From my experience, almost always methods parameters must not be null in AM

Then that is great! After enabling nullable reference types, little code changes will be required,

**Comment by Happypig375** [comment]
>Could you at least put examples where this feature can be used in our library?

Put
```
<Nullable>enable</Nullable>
<WarningsAsErrors>nullable</WarningsAsErrors>
```
in the `csproj`s.

**Comment by Happypig375** [comment]
@siriak The green light is needed or https://github.com/LayoutFarm/Typography/pull/192 will happen again.

**Comment by siriak** [comment]
@Happypig375 agree, good point.

**Comment by MomoDeve** [comment]
We will look at the changes. If all unit tests are passed, we will merge it

**Comment by Happypig375** [comment]
I have started to implement this.
