### ISSUE TITLE
how to write a string which  can create nth root latex

### ISSUE THREAD

**Issue by chrismx000** [asc-community/AngouriMath#603]
hi，this is a great project!
recently,i find the way to create 3th root latex,just like this  "cbrt(5)".Latexise()   ==>  res: \sqrt[3]{5}  
but how to write a string that can create the latex like  \sqrt[n]{m}   ?

**Comment by WhiteBlackGoose** [comment]
Hi!
`cbrt` is in fact [just a shorthand](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Convenience/MathS.cs#L492) for power 1/3. So all you need is to write "5^(1/5)".

But using a variable or expression as the power of the root? Currently [only](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Functions/Output/Latex/Latex.Arithmetics.Classes.cs#L93) rational numbers are suported, unfortunately. Perhaps we need a separate node for root, but as for now, it's unclear when we should interpreted `1/{expression}` as a root or as power.

**Comment by chrismx000** [comment]
ennn，I see. Thank you for your reply。
