### ISSUE TITLE
how to use != in expression 

### ISSUE THREAD

**Issue by chrismx000** [asc-community/AngouriMath#605]
In my case 
`var str = "a!=6";
Entity expr=str;
var con=expr.Compile<double,bool>("a");
Console.WriteLine($"res={con(5.0)}");
// console => res=False;
`
actually,it should retuan true.
what should i do?

**Comment by chrismx000** [comment]
oh,your right,it works. but  is there any way to write an expression  which can create the latex of ≠?

**Comment by WhiteBlackGoose** [comment]
I'm afraid, no. You can create your own node, `NotEqual`, similar to [equality node](https://github.com/asc-community/AngouriMath/blob/master/Sources/AngouriMath/AngouriMath/Core/Entity/Discrete/Entity.Discrete.Classes.cs#L197)

**Comment by chrismx000** [comment]
Okay, I'll try，thanks a lot.
