### ISSUE TITLE
Cannot get 9+6*x+x^2 from (x+3)^2

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#61]
Expand: x\*x+x\*3+3\*x+3\*3
Expand+Simplify: 9+(6+x)*x

**Comment by WhiteBlackGoose** [comment]
Right, expand is quite silly, and simplify is quite overkill for it. Yet not clear how to solve this minor issue

**Comment by Happypig375** [comment]
Same goes for factor. There are exponents like `2/2` that should be simplified.

**Comment by Happypig375** [comment]
Maybe some rules currently only in `Simplify` can be shared between `Simplify`, `Collapse` and `Expand`

**Comment by WhiteBlackGoose** [comment]
MathS.Utils.TryPolynomial added

**Comment by Happypig375** [comment]
Solution is incomplete. There is no way to get `cos(x)^2+2*cos(x)+1` from `cos(x)+1)^2`.
