### ISSUE TITLE
Consider adding support for StringSyntax attribute

### ISSUE THREAD

**Issue by irunjic** [asc-community/AngouriMath#611]
It would be helpful to have syntax highlighting. For example:

https://www.infoq.com/news/2022/11/visual-studio-tagged-strings/

**Comment by WhiteBlackGoose** [comment]
Hi, thanks for the suggestion. Is it VS-only thing? Doesn't seem to work on OmniSharp yet, so I won't be able to test it.

**Comment by WhiteBlackGoose** [comment]
I see. If OmniSharp (language server) adds support for it, I may be able to do something for it. Or if any contributor is willing to do it.
