### ISSUE TITLE
Order polynomials from highest degree to lowest degree after simplifying

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#62]

**Comment by WhiteBlackGoose** [comment]
Impossible, you cannot predict which variable is the "main" one. But we probably may implement method for constructing a polynomial over a variable, e. g.
```
MathS.GetPolynomial(expr, "x")
```
Not sure if it's needed though

**Comment by Happypig375** [comment]
>Impossible, you cannot predict which variable is the "main" one.

There is already a sort performed by `Simplify` which sorts variables according to their alphabetical order. On top of this, we should follow the mathematical norm of writing higher powers of the same variable first.

**Comment by Happypig375** [comment]
So in top of `y^2+x^2`->`x^2+y^2` we would also have `x^2+x`->`x+x^2`.

**Comment by WhiteBlackGoose** [comment]
MathS.Utils.TryPolynomial added

**Comment by Happypig375** [comment]
@WhiteBlackGoose TryPolynomial is not able to support multiple variables though. I said
>There is already a sort performed by `Simplify` which sorts variables according to their alphabetical order. On top of this, we should follow the mathematical norm of writing higher powers of the same variable first.
>So on top of y^2+x^2->x^2+y^2 we would also have x+x^2->x^2+x.

**Comment by Happypig375** [comment]
In addition, functions like `cos(x)` can also follow the alphabetical order of `cos`.
