### ISSUE TITLE
Any easy way to change the behaviour when parsing alpha_num pattern string?

### ISSUE THREAD

**Issue by ShannonZ** [asc-community/AngouriMath#626]
Currently, an alpha_num pattern string (for example, x2 , y3, T21) would be interpreted as 'pow(alpha,num)'.
**Is there any way to change the default behavior?**

I wanna interpret 'x2' as a variable, whose name is 'x2'. Then interpret x^2 as 'pow(x,2)'.

Here are some cases in my situation:
k * x+b                                  interpreted as                       `  (x,k,b)=>k*x+b`
A1 * t1+A2 * t2+A0                 interpreted as                       ` (A1,t1,A2,t2,A0)=>A1*t1+A2*t2+A0`
exp(-t/T)+bias ^ 4                       interpreted as                `  (t,T,bias) => Math.Exp(-t/T)+Math.Pow(bias,4)`

**Comment by WhiteBlackGoose** [comment]
Yes, you need to enable explicit parser in MathS.Settings

**Comment by ShannonZ** [comment]
Any demos or docs about how to? @WhiteBlackGoose

**Comment by WhiteBlackGoose** [comment]
Ah no, I was wrong. The [docs](https://am.angouri.org/docs/AngouriMath.MathS/Settings/ExplicitParsingOnly.html) are here, but `a2` will _probably_ be interpreted as wrongly written `a^2` and throw an exception. If that's the case, use `_` as a delimiter between the variable and the index, e. g. `a_2`.

**Comment by ShannonZ** [comment]
In my situation, there are several proper nouns like T23, T24, T25.

**Comment by WhiteBlackGoose** [comment]
`T_23` is legal

**Comment by ShannonZ** [comment]
I got it!
