### ISSUE TITLE
Extracting Numerical Values from  Solve Method Results

### ISSUE THREAD

**Issue by Finally-Fantasy** [asc-community/AngouriMath#636]
I don’t know how to get the numerical value from the calculation result. The Solve method returns a type AngouriMath.Entity.Set, for example,Entity expr = "x2 = 16";
Console.WriteLine(expr.Solve("x"));
-> {4, -4}.
 How can I extract the value 4 or -4?

**Comment by Finally-Fantasy** [comment]
In some cases, the solution to the equation is a fraction, such as { 3/2 }, which is even more troublesome. I have no idea how to extract the numerical value 1.5 from it.

**Comment by WhiteBlackGoose** [comment]
You can cast it to FiniteSet and then iterate over it

**Comment by WhiteBlackGoose** [comment]
https://am.angouri.org/wiki/Solvers.html

**Comment by Finally-Fantasy** [comment]
thanks
