### ISSUE TITLE
Add periodic roots for complex exponent solver

### ISSUE THREAD

**Issue by MomoDeve** [asc-community/AngouriMath#68]
Solving following equation returning only one solution:
```cs
var expr = MathS.FromString("e^(i*x) - 0.5");
var sol = MathS.SolveEquation(expr, "x");
```
But actually this equation has inifinite number of periodic roots (example from WolframAlpha):
https://www.wolframalpha.com/input/?i=e%5Eix+%3D+0.5

**Comment by Happypig375** [comment]
Infinite solution sets!

**Comment by MomoDeve** [comment]
> Infinite solution sets!

Technically they are already exists: for example the result of solving the equation sin(x) = a. It just adds variable n to the result

**Comment by siriak** [comment]
Is this the answer we are looking for?
![image](https://user-images.githubusercontent.com/29201949/80860958-0834e280-8c74-11ea-8a07-97ca64549527.png)

**Comment by MomoDeve** [comment]
> Is this the answer we are looking for?
> ![image](https://user-images.githubusercontent.com/29201949/80860958-0834e280-8c74-11ea-8a07-97ca64549527.png)

Yes, we just need to implement it and handle all corner cases =)

**Comment by WhiteBlackGoose** [comment]
Fixed
