### ISSUE TITLE
Check if n is already used when solving for multiple solutions

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#69]
For example, Wolfram Alpha uses c_1 instead when n is present.

**Comment by WhiteBlackGoose** [comment]
Will be released as soon as sets. Im working on it

**Comment by MomoDeve** [comment]
I suggested @WhiteBlackGoose to implement it with unicode subscripts, i.e. n₁, but seems like he disliked my solution. If we want to stick to regular ascii numbers, we need to reimplement expression parser as a first step

**Comment by Happypig375** [comment]
Nice

**Comment by WhiteBlackGoose** [comment]
Fixed
