### ISSUE TITLE
x^2+y^2+2x*y+w -> w+x^2+2x*y+y^2

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#73]
https://github.com/asc-community/AngouriMath/issues/62#issuecomment-619848937

TryPolynomial is not able to support multiple variables though. I said
There is already a sort performed by Simplify which sorts variables according to their alphabetical order. On top of this, we should follow the mathematical norm of writing higher powers of the same variable first.
So on top of y^2+x^2->x^2+y^2 we would also have x+x^2->x^2+x.
So multiple variables like x^2+y^2+2x*y+w would first sort by w, then x, finally y: w+x^2+2x*y+y^2

In addition, functions like cos(x) can also follow the alphabetical order of cos.

**Comment by WhiteBlackGoose** [comment]
I don't see how it is useful. I will probably expose patterns for users, so users could customize such functions.
