### ISSUE TITLE
Sets should be Entities

### ISSUE THREAD

**Issue by Happypig375** [asc-community/AngouriMath#83]
Sets should support operations on entities, such as arithmetic and functions.

**Comment by WhiteBlackGoose** [comment]
Ariphmetic operations cannot be performed on sets

**Comment by Happypig375** [comment]
They can. It's performed elementwise. https://www.wolframalpha.com/input/?i=%7B1%2C2%2C3%7D+%2B+1

**Comment by Happypig375** [comment]
https://www.wolframalpha.com/input/?i=%7B1%2C2%2C3%7D%2B%7B1%2C2%2C7%7D

**Comment by MomoDeve** [comment]
Maybe use functions like map and zip?

**Comment by WhiteBlackGoose** [comment]
No, they cannot be. Sets are normally infinite, and processing some special cases is not a good, logical idea. Maybe Ill develop "FiniteSet" further, such set will support these opearations

**Comment by Happypig375** [comment]
What about e.g. interval arithmetic?

**Comment by WhiteBlackGoose** [comment]
What do you mean? You cannot perform almost any ariphmetic operations on infinite sets. + and - aside, imagine you need to get square of an interval [-2; 2]. The result is [0; 4]. Likewise, other operations behave unpredictably and may even not have an interval form

**Comment by WhiteBlackGoose** [comment]
Alright, it's been decided to make this real
