### ISSUE TITLE
I want to contact with you

### ISSUE THREAD

**Issue by GuguMath** [asc-community/AngouriMath#85]
I am impressed with this project so can you give me your email to contact? I want to ask you something

**Comment by MomoDeve** [comment]
@GuguMath use email WhiteBlackGoose@asc-community.org to contact WhiteBlackGoose (creator and main developer of this project) or mine - alexander.potapov.w@yandex.ru

**Comment by GuguMath** [comment]
@MomoDeve Ok i contact with this email (WhiteBlackGoose@asc-community.org). Thanks you!

**Comment by WhiteBlackGoose** [comment]
@GuguMath hey, I hope you got my e-mail. Experienced some problems with sending from a new address
