### ISSUE TITLE
Extend pattern-matching functionality

### ISSUE THREAD

**Issue by MomoDeve** [asc-community/AngouriMath#87]
For now patterns supports `any` which stands for `any Entity`, `const` which stands for `any Number`, `Num(x)` which stands for `specific Number` and functions applied as `Func.PHang`.

I would like to see pattern `Variable(x)` which stands for specific variable same as `Num(x)` stands for specific value. So like with pattern `Variable("x") * const` `x*3` will match, but `y*3` won't.

Why this is useful? With that when you solve expression for specific variable, you can use patterns to find subtree. For example if pattern is `Sinf.PHang(Patterns.const1 * Patterns.Variable("x") + Patterns.const2)`, we could retrieve `sin(a * x + b)` from expression. With that is would become possible to extend functionality of `TreeAnalyzer.FindAndReplace()` if we dont know what to replace exactly

**Comment by WhiteBlackGoose** [comment]
Custom delegates for patterns added. For example, you can set in runtime
```cs
var variablePattern = new Pattern(1000, Entity.PatType.VARIABLE, 
                tree => tree.entType == Entity.EntType.VARIABLE && tree.Name == "x");
// This will only work for variables that are x
var variablePattern = new Pattern(1000, Entity.PatType.VARIABLE, 
                tree => tree.entType == Entity.EntType.VARIABLE && tree.FindSubtree("x + 2") != null);
This one would work for all trees containing "x + 2"
```
